// Generated by gencpp from file cv/date.msg
// DO NOT EDIT!


#ifndef CV_MESSAGE_DATE_H
#define CV_MESSAGE_DATE_H

#include <ros/service_traits.h>


#include <cv/dateRequest.h>
#include <cv/dateResponse.h>


namespace cv
{

struct date
{

typedef dateRequest Request;
typedef dateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct date
} // namespace cv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cv::date > {
  static const char* value()
  {
    return "bd888d811c7cb3be0c1173dc8d4d390b";
  }

  static const char* value(const ::cv::date&) { return value(); }
};

template<>
struct DataType< ::cv::date > {
  static const char* value()
  {
    return "cv/date";
  }

  static const char* value(const ::cv::date&) { return value(); }
};


// service_traits::MD5Sum< ::cv::dateRequest> should match
// service_traits::MD5Sum< ::cv::date >
template<>
struct MD5Sum< ::cv::dateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cv::date >::value();
  }
  static const char* value(const ::cv::dateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv::dateRequest> should match
// service_traits::DataType< ::cv::date >
template<>
struct DataType< ::cv::dateRequest>
{
  static const char* value()
  {
    return DataType< ::cv::date >::value();
  }
  static const char* value(const ::cv::dateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cv::dateResponse> should match
// service_traits::MD5Sum< ::cv::date >
template<>
struct MD5Sum< ::cv::dateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cv::date >::value();
  }
  static const char* value(const ::cv::dateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cv::dateResponse> should match
// service_traits::DataType< ::cv::date >
template<>
struct DataType< ::cv::dateResponse>
{
  static const char* value()
  {
    return DataType< ::cv::date >::value();
  }
  static const char* value(const ::cv::dateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CV_MESSAGE_DATE_H
