// Generated by gencpp from file Serial/dateResponse.msg
// DO NOT EDIT!


#ifndef SERIAL_MESSAGE_DATERESPONSE_H
#define SERIAL_MESSAGE_DATERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Serial
{
template <class ContainerAllocator>
struct dateResponse_
{
  typedef dateResponse_<ContainerAllocator> Type;

  dateResponse_()
    : x(0)
    , y(0)  {
    }
  dateResponse_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::Serial::dateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Serial::dateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct dateResponse_

typedef ::Serial::dateResponse_<std::allocator<void> > dateResponse;

typedef boost::shared_ptr< ::Serial::dateResponse > dateResponsePtr;
typedef boost::shared_ptr< ::Serial::dateResponse const> dateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Serial::dateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Serial::dateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::Serial::dateResponse_<ContainerAllocator1> & lhs, const ::Serial::dateResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::Serial::dateResponse_<ContainerAllocator1> & lhs, const ::Serial::dateResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace Serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::Serial::dateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Serial::dateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Serial::dateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Serial::dateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Serial::dateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Serial::dateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Serial::dateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd7b43fd41d4c47bf5c703cc7d016709";
  }

  static const char* value(const ::Serial::dateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd7b43fd41d4c47bULL;
  static const uint64_t static_value2 = 0xf5c703cc7d016709ULL;
};

template<class ContainerAllocator>
struct DataType< ::Serial::dateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Serial/dateResponse";
  }

  static const char* value(const ::Serial::dateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Serial::dateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::Serial::dateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Serial::dateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Serial::dateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Serial::dateResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_MESSAGE_DATERESPONSE_H
