// Generated by gencpp from file Serial/date.msg
// DO NOT EDIT!


#ifndef SERIAL_MESSAGE_DATE_H
#define SERIAL_MESSAGE_DATE_H

#include <ros/service_traits.h>


#include <Serial/dateRequest.h>
#include <Serial/dateResponse.h>


namespace Serial
{

struct date
{

typedef dateRequest Request;
typedef dateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct date
} // namespace Serial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Serial::date > {
  static const char* value()
  {
    return "bd888d811c7cb3be0c1173dc8d4d390b";
  }

  static const char* value(const ::Serial::date&) { return value(); }
};

template<>
struct DataType< ::Serial::date > {
  static const char* value()
  {
    return "Serial/date";
  }

  static const char* value(const ::Serial::date&) { return value(); }
};


// service_traits::MD5Sum< ::Serial::dateRequest> should match
// service_traits::MD5Sum< ::Serial::date >
template<>
struct MD5Sum< ::Serial::dateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Serial::date >::value();
  }
  static const char* value(const ::Serial::dateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Serial::dateRequest> should match
// service_traits::DataType< ::Serial::date >
template<>
struct DataType< ::Serial::dateRequest>
{
  static const char* value()
  {
    return DataType< ::Serial::date >::value();
  }
  static const char* value(const ::Serial::dateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Serial::dateResponse> should match
// service_traits::MD5Sum< ::Serial::date >
template<>
struct MD5Sum< ::Serial::dateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Serial::date >::value();
  }
  static const char* value(const ::Serial::dateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Serial::dateResponse> should match
// service_traits::DataType< ::Serial::date >
template<>
struct DataType< ::Serial::dateResponse>
{
  static const char* value()
  {
    return DataType< ::Serial::date >::value();
  }
  static const char* value(const ::Serial::dateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERIAL_MESSAGE_DATE_H
